### PR TITLE
Initiated the historical data API calls

### PR DESCRIPTION
**Pull request by aymanrb**

### CODE REVIEW

**Comment by aymanrb** [comment]
@mos3abof ... Any hope we can get this merged, I was working an app that will require the historical data in the very near future

If that's not what you expected the API to do let me know your ideas and I can craft something with it if the time permits

**Comment by mos3abof** [comment]
>
> Hello Ayman,
>

I will review the changes and let you know soon. I sincerely thank you for
the contribution.

Whether your pull request is accepted or not, here is a little token of
thanks.

I got an open source license for PHPStorm, and I am legally allowed to
share it with the contributors of Grid Status Now project, so here is your
license key quoting the installation process they emailed me:


=========INSTALLATION==========
>
> Run PhpStorm and follow the Installation Wizard's instructions. To
> register for use of the software or change your existing registration
> details, go to Help/Register menu of the software and enter the User Name
> and License Key(s) included below into the registration dialog:
>
> User Name: Grid Status Now
>
> ===== LICENSE BEGIN =====
> 846440-19122014
> 00001ZFxgGC40wanAC09"I"!hpv9dh
> IuWzLL0!LZQz0lFv6dsJAs!nEwk!7e
> hX0y!Rho0Oqw8TbaycDP3kzXpxHT99
> ===== LICENSE END =====
>

Please note that you must not share this key with anybody without my
approval first and without them being contributors to the project. This may
end in revoking of the license for all of us.

I thank you again.

Regards.




Mosab Ahmad
about.me/mosab.ahmad
  [image: Mosab Ahmad on about.me]

**Comment by aymanrb** [comment]
Great thankyou for sharing ... Just note that by replying to the mail your message is added as a reply to the pull request conversation. The key is already in public view now :) so please edit it.

Looking forward to hearing from you on this whenever you get the time to review the changes.

**Comment by mos3abof** [comment]
I am reviewing the code and will have a reply soon. 

Thanks :)

**Pull request closed without merging**
